/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GroveRouteImport } from './routes/grove'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GroveRoute = GroveRouteImport.update({
  id: '/grove',
  path: '/grove',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customize': typeof CustomizeRoute
  '/friends': typeof FriendsRoute
  '/grove': typeof GroveRoute
  '/journal': typeof JournalRoute
  '/parent': typeof ParentRoute
  '/quests': typeof QuestsRoute
  '/shop': typeof ShopRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customize': typeof CustomizeRoute
  '/friends': typeof FriendsRoute
  '/grove': typeof GroveRoute
  '/journal': typeof JournalRoute
  '/parent': typeof ParentRoute
  '/quests': typeof QuestsRoute
  '/shop': typeof ShopRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customize': typeof CustomizeRoute
  '/friends': typeof FriendsRoute
  '/grove': typeof GroveRoute
  '/journal': typeof JournalRoute
  '/parent': typeof ParentRoute
  '/quests': typeof QuestsRoute
  '/shop': typeof ShopRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customize'
    | '/friends'
    | '/grove'
    | '/journal'
    | '/parent'
    | '/quests'
    | '/shop'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customize'
    | '/friends'
    | '/grove'
    | '/journal'
    | '/parent'
    | '/quests'
    | '/shop'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/customize'
    | '/friends'
    | '/grove'
    | '/journal'
    | '/parent'
    | '/quests'
    | '/shop'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomizeRoute: typeof CustomizeRoute
  FriendsRoute: typeof FriendsRoute
  GroveRoute: typeof GroveRoute
  JournalRoute: typeof JournalRoute
  ParentRoute: typeof ParentRoute
  QuestsRoute: typeof QuestsRoute
  ShopRoute: typeof ShopRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grove': {
      id: '/grove'
      path: '/grove'
      fullPath: '/grove'
      preLoaderRoute: typeof GroveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomizeRoute: CustomizeRoute,
  FriendsRoute: FriendsRoute,
  GroveRoute: GroveRoute,
  JournalRoute: JournalRoute,
  ParentRoute: ParentRoute,
  QuestsRoute: QuestsRoute,
  ShopRoute: ShopRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
